export const Home = '/'
export const Login = '/login'
export const Dashboard = '/dashboard'
export const ForgetPassword = '/forgetpassword'
export const ChangePassword = '/changepassword'
export const Users = '/users'
export const Services = '/services'